list packages in reboot check

diff --git a/checks/check_reboot b/checks/check_reboot
--- a/checks/check_reboot
+++ b/checks/check_reboot
@@ -2,15 +2,16 @@
 #This is a quick check to see if system needs rebooting due to package upgrade.
 #Returns nagios ok if no reboot required, critcial if reboot is required.
 if [ -f /var/run/reboot-required ]; then
-        echo 'REBOOT check CRITICAL'
-        echo "Package upgrades require reboot"
-        exit 2;
+	echo 'REBOOT check CRITICAL'
+	echo "Reboot required due to packages:"
+	cat /var/run/reboot-required.pkgs
+	exit 2;
 elif [ -s /var/lib/update-notifier/fsck-at-reboot ]; then
-        echo 'REBOOT check WARNING'
-        echo "A disk needs fscking on next reboot"
-        exit 1;
+	echo 'REBOOT check WARNING'
+	echo "A disk needs fscking on next reboot"
+	exit 1;
 else
-        echo "REBOOT check OK"
-        exit 0;
+	echo "REBOOT check OK"
+	exit 0;
 fi
 
